version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019 Preview
install:
  - git submodule update --init --recursive
  - ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe'
  - ps: Start-Process .\dotnet-sdk-latest-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
  
platform:
  - Any CPU

configuration:
  - Release

before_build:
  - ps: nuget restore src/Dependencies.Viewer.sln

build:
  project: src/Dependencies.Viewer.sln
  verbosity: minimal

artifacts:
  - path: Build\Release
    name: Dependencies Viewer
    type: zip